// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Placeholder values keep the app from crashing on load when .env is missing;
// src/main.tsx shows a setup screen in that case instead of the store.
export const supabase = createClient<Database>(SUPABASE_URL || "https://missing-env.supabase.co", SUPABASE_PUBLISHABLE_KEY || "missing-env", {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});